/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_projects__project_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Line Items */
        get: operations["list_line_items_api_projects__project_id__line_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Suppliers */
        get: operations["list_project_suppliers_api_projects__project_id__suppliers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quotes */
        get: operations["list_quotes_api_projects__project_id__quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rfqs */
        get: operations["list_rfqs_api_projects__project_id__rfqs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfq-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rfq Folders */
        get: operations["list_rfq_folders_api_projects__project_id__rfq_folders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_projects__project_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/packages/{pkg}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_api_projects__project_id__packages__pkg__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/packages/{pkg}/line-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Line Comparison
         * @description Line-by-line quote grid + freight-aware mix-and-match award strategies.
         */
        get: operations["get_line_comparison_api_projects__project_id__packages__pkg__line_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/packages/{pkg}/award": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Award Package
         * @description Submit a (possibly split) award for a package and issue the purchase orders.
         */
        post: operations["award_package_api_projects__project_id__packages__pkg__award_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/packages/{package}/search-suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Suppliers */
        post: operations["search_suppliers_api_projects__project_id__packages__package__search_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/suppliers/found": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Found Suppliers */
        get: operations["get_found_suppliers_api_projects__project_id__suppliers_found_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/quotes/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Quotes
         * @description Kick off reading supplier quote replies for a project (background task).
         *
         *     The frontend then polls GET .../quotes/ingest-status until it leaves
         *     'ingesting', then refreshes the quotes table + comparison.
         */
        post: operations["ingest_quotes_api_projects__project_id__quotes_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/quotes/ingest-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingest Status */
        get: operations["get_ingest_status_api_projects__project_id__quotes_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/packages/{package}/rfqs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Rfq */
        post: operations["generate_rfq_api_projects__project_id__packages__package__rfqs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfqs/generated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Generated Rfqs */
        get: operations["list_generated_rfqs_api_projects__project_id__rfqs_generated_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfqs/{rfq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generated Rfq */
        get: operations["get_generated_rfq_api_projects__project_id__rfqs__rfq_id__get"];
        /** Update Generated Rfq */
        put: operations["update_generated_rfq_api_projects__project_id__rfqs__rfq_id__put"];
        post?: never;
        /** Delete Generated Rfq */
        delete: operations["delete_generated_rfq_api_projects__project_id__rfqs__rfq_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfqs/{rfq_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rfq Conversation
         * @description Full email thread for an RFQ, read live from Gmail when configured.
         *
         *     Read-only: we surface the original Gmail thread (our outbound plus any
         *     threaded supplier replies) without changing the RFQ's status.
         */
        get: operations["get_rfq_conversation_api_projects__project_id__rfqs__rfq_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/rfqs/{rfq_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Generated Rfq */
        post: operations["send_generated_rfq_api_projects__project_id__rfqs__rfq_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_suppliers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier */
        get: operations["get_supplier_api_suppliers__supplier_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/plan-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plan Types
         * @description Plan types the extractor supports — drives the upload selector.
         */
        get: operations["list_plan_types_api_documents_plan_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a document, its extracted BOM, and any uploaded source file.
         */
        delete: operations["delete_document_api_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document File
         * @description Serve the original uploaded file inline so the frontend can preview it.
         *
         *     Only uploaded documents have a `source_path` on disk; seed/demo docs return
         *     404 and the UI falls back to its placeholder.
         */
        get: operations["get_document_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Line Items
         * @description BOM groups extracted from one document.
         */
        get: operations["get_document_line_items_api_documents__document_id__line_items_get"];
        /**
         * Save Document Line Items
         * @description Human-in-the-loop: replace a document's BOM with the reviewer's edits.
         *
         *     Recomputes group counts and the document's item total, and flags it as edited.
         */
        put: operations["save_document_line_items_api_documents__document_id__line_items_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Document
         * @description Human-in-the-loop: mark a document's BOM as reviewed and approved.
         */
        post: operations["confirm_document_api_documents__document_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a plan set and kick off background AI extraction. The document is
         *     attached to `project_id` so each project keeps its own document list.
         */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Document
         * @description Re-run extraction for an already-uploaded document.
         */
        post: operations["analyze_document_api_documents__document_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{rfq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rfq */
        get: operations["get_rfq_api_rfqs__rfq_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{rfq_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Command: post a reply to an RFQ thread.
         */
        post: operations["send_message_api_rfqs__rfq_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rfqs/{rfq_id}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Followup
         * @description Command: generate an AI follow-up nudge for a non-responsive supplier.
         *
         *     Stubbed — returns a templated message. Replace with an LLM call.
         */
        post: operations["draft_followup_api_rfqs__rfq_id__followup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_quotes__quote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/{quote_id}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Quote
         * @description Command: select a supplier's quote and issue a purchase order.
         */
        post: operations["select_quote_api_quotes__quote_id__select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Icon */
            icon: string;
            tone: components["schemas"]["Tone"];
            /** Title */
            title: string;
            /** Meta */
            meta: string;
            /** Time */
            time: string;
        };
        /** AwardOption */
        AwardOption: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Total */
            total: number;
            /** Material */
            material: number;
            /** Freight */
            freight: number;
            /** Leaddays */
            leadDays?: number | null;
            /** Suppliersused */
            suppliersUsed: number;
            /** Deliveries */
            deliveries: number;
            /** Maxdistance */
            maxDistance?: number | null;
            /**
             * Savings
             * @default 0
             */
            savings: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Selections
             * @default {}
             */
            selections: {
                [key: string]: string;
            };
        };
        /** AwardRequest */
        AwardRequest: {
            /** Selections */
            selections: {
                [key: string]: string;
            };
            /** Strategy */
            strategy?: string | null;
        };
        /** AwardResult */
        AwardResult: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Total */
            total: number;
            /** Material */
            material: number;
            /** Freight */
            freight: number;
            /** Leaddays */
            leadDays?: number | null;
            /** Suppliers */
            suppliers: string[];
            /** Pocount */
            poCount: number;
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Plan Type */
            plan_type?: string;
            /**
             * Project Id
             * @default riverside
             */
            project_id: string;
        };
        /** Comparison */
        Comparison: {
            /** Pkg */
            pkg: string;
            /** Suppliers */
            suppliers: components["schemas"]["ComparisonSupplier"][];
            /** Rows */
            rows: components["schemas"]["ComparisonRow"][];
            /** Recommendation */
            recommendation: string;
            /** Reasons */
            reasons: string[];
            /** Savings */
            savings: string;
            /** Savingsnote */
            savingsNote: string;
        };
        /** ComparisonRow */
        ComparisonRow: {
            /** Label */
            label: string;
            /** Vals */
            vals: string[];
            /** Best */
            best: number;
            /**
             * Emph
             * @default false
             */
            emph: boolean;
        };
        /** ComparisonSupplier */
        ComparisonSupplier: {
            /** Name */
            name: string;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            /**
             * Rec
             * @default false
             */
            rec: boolean;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /** Dir */
            dir: string;
            /** Who */
            who: string;
            /** Initials */
            initials: string;
            /** Time */
            time: string;
            /** Body */
            body: string;
            /** Subject */
            subject?: string | null;
            /** Attach */
            attach?: string | null;
            /** Logobg */
            logoBg?: string | null;
        };
        /** Dashboard */
        Dashboard: {
            /** Metrics */
            metrics: components["schemas"]["Metric"][];
            /** Activity */
            activity: components["schemas"]["Activity"][];
        };
        /**
         * DocStatus
         * @enum {string}
         */
        DocStatus: "Queued" | "Processing" | "Analyzed" | "Failed";
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Date */
            date: string;
            status: components["schemas"]["DocStatus"];
            statusTone: components["schemas"]["Tone"];
            /** Items */
            items: string;
            /** Pages */
            pages: number;
            /**
             * Processing
             * @default false
             */
            processing: boolean;
            /**
             * Hasfile
             * @default false
             */
            hasFile: boolean;
            /** Plantype */
            planType?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Mocked
             * @default false
             */
            mocked: boolean;
            /** Error */
            error?: string | null;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Reviewedat */
            reviewedAt?: string | null;
            /**
             * Edited
             * @default false
             */
            edited: boolean;
        };
        /** FollowupDraft */
        FollowupDraft: {
            /** Body */
            body: string;
        };
        /** FoundSupplier */
        FoundSupplier: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Distancemiles */
            distanceMiles: number;
            /** Tier */
            tier: number;
            /** Contactname */
            contactName?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /**
             * Materialcategories
             * @default []
             */
            materialCategories: string[];
            /**
             * Emailsource
             * @default none
             */
            emailSource: string;
        };
        /** GanttBar */
        GanttBar: {
            /** Name */
            name: string;
            /** Start */
            start: number;
            /** Len */
            len: number;
            tone: components["schemas"]["Tone"];
            /** Label */
            label: string;
            /**
             * Warn
             * @default false
             */
            warn: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineCompareCell */
        LineCompareCell: {
            /** Supplierid */
            supplierId: string;
            /** Unitprice */
            unitPrice?: number | null;
            /** Extended */
            extended?: number | null;
            /** Leaddays */
            leadDays?: number | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Best
             * @default false
             */
            best: boolean;
        };
        /** LineCompareRow */
        LineCompareRow: {
            /** Name */
            name: string;
            /**
             * Qty
             * @default
             */
            qty: string;
            /** Cells */
            cells: components["schemas"]["LineCompareCell"][];
            /** Bestsupplierid */
            bestSupplierId?: string | null;
        };
        /** LineCompareSupplier */
        LineCompareSupplier: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            /** Leaddays */
            leadDays?: number | null;
            /** Distancemiles */
            distanceMiles?: number | null;
            /** Freight */
            freight?: number | null;
            /** Total */
            total?: number | null;
        };
        /** LineComparison */
        LineComparison: {
            /** Pkg */
            pkg: string;
            /** Package */
            package: string;
            /** Budget */
            budget?: number | null;
            /** Suppliers */
            suppliers: components["schemas"]["LineCompareSupplier"][];
            /** Lines */
            lines: components["schemas"]["LineCompareRow"][];
            /** Options */
            options: components["schemas"]["AwardOption"][];
            /**
             * Recommendedoption
             * @default mix
             */
            recommendedOption: string;
        };
        /** LineItem */
        LineItem: {
            /** N */
            n: string;
            /** Q */
            q: string;
        };
        /** LineItemGroup */
        LineItemGroup: {
            /** Group */
            group: string;
            /** Count */
            count: number;
            tone: components["schemas"]["Tone"];
            /** Items */
            items: components["schemas"]["LineItem"][];
        };
        /**
         * LineItemsUpdate
         * @description Body for saving a human-edited BOM (full replacement of the groups).
         */
        LineItemsUpdate: {
            /** Groups */
            groups: components["schemas"]["LineItemGroup"][];
        };
        /** MessageCreate */
        MessageCreate: {
            /** Body */
            body: string;
        };
        /** Metric */
        Metric: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Delta */
            delta: string;
            /**
             * Sub
             * @default
             */
            sub: string;
            /**
             * Up
             * @default false
             */
            up: boolean;
            /**
             * Down
             * @default false
             */
            down: boolean;
            /**
             * Ai
             * @default false
             */
            ai: boolean;
            /**
             * Risk
             * @default false
             */
            risk: boolean;
        };
        /** Milestone */
        Milestone: {
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Status */
            status: string;
            /** Desc */
            desc: string;
            tone: components["schemas"]["Tone"];
            /**
             * Done
             * @default false
             */
            done: boolean;
            /**
             * Active
             * @default false
             */
            active: boolean;
        };
        /** OverviewCard */
        OverviewCard: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Sub */
            sub: string;
            /** Icon */
            icon: string;
            tone: components["schemas"]["Tone"];
            /**
             * Ai
             * @default false
             */
            ai: boolean;
        };
        /** Package */
        Package: {
            /** Name */
            name: string;
            /** Pct */
            pct: number;
            tone: components["schemas"]["Tone"];
        };
        /**
         * PersistedRfq
         * @description An RFQ generated from a buy-package, stored per project.
         */
        PersistedRfq: {
            /** Id */
            id: string;
            /** Sup */
            sup: string;
            /** Pkg */
            pkg: string;
            /** Folder */
            folder: string;
            status: components["schemas"]["RfqStatus"];
            statusTone: components["schemas"]["Tone"];
            /** Preview */
            preview: string;
            /** Time */
            time: string;
            /**
             * Unread
             * @default false
             */
            unread: boolean;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            /** Projectid */
            projectId: string;
            /** Package */
            package: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /**
             * Lineitems
             * @default []
             */
            lineItems: components["schemas"]["RfqLineItem"][];
            /**
             * Recipients
             * @default []
             */
            recipients: components["schemas"]["RfqRecipient"][];
        };
        /**
         * PlanType
         * @description A registered plan type, surfaced to the upload UI.
         */
        PlanType: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Categories */
            categories: string[];
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Loc */
            loc: string;
            stage: components["schemas"]["Stage"];
            stageTone: components["schemas"]["Tone"];
            /** Value */
            value: string;
            /** Progress */
            progress: number;
            /** Suppliers */
            suppliers: number;
            /** Rfqs */
            rfqs: number;
            /** Quotes */
            quotes: number;
            risk: components["schemas"]["Risk"];
            riskTone: components["schemas"]["Tone"];
            /** Barcolor */
            barColor: string;
        };
        /**
         * ProjectCreate
         * @description Payload for creating a project from the New project modal.
         */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Loc
             * @default
             */
            loc: string;
            /**
             * Value
             * @default
             */
            value: string;
            /** @default Plans Review */
            stage: components["schemas"]["Stage"];
        };
        /**
         * ProjectDetail
         * @description Full project workspace payload.
         */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Loc */
            loc: string;
            stage: components["schemas"]["Stage"];
            stageTone: components["schemas"]["Tone"];
            /** Value */
            value: string;
            /** Progress */
            progress: number;
            /** Suppliers */
            suppliers: number;
            /** Rfqs */
            rfqs: number;
            /** Quotes */
            quotes: number;
            risk: components["schemas"]["Risk"];
            riskTone: components["schemas"]["Tone"];
            /** Barcolor */
            barColor: string;
            /** Overviewcards */
            overviewCards: components["schemas"]["OverviewCard"][];
            /** Packages */
            packages: components["schemas"]["Package"][];
        };
        /** Quote */
        Quote: {
            /** Id */
            id: string;
            /** Sup */
            sup: string;
            /** Pkg */
            pkg: string;
            /** Amount */
            amount: string;
            /** Freight */
            freight: string;
            /** Total */
            total: string;
            /** Lead */
            lead: string;
            /** Date */
            date: string;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            /**
             * Best
             * @default false
             */
            best: boolean;
        };
        /**
         * QuoteIngestResult
         * @description Status payload for the quote-ingest poller (mirrors the search poller).
         */
        QuoteIngestResult: {
            /** Status */
            status: string;
            /**
             * Mocked
             * @default false
             */
            mocked: boolean;
            /**
             * Ingested
             * @default 0
             */
            ingested: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Error */
            error?: string | null;
        };
        /** Rfq */
        Rfq: {
            /** Id */
            id: string;
            /** Sup */
            sup: string;
            /** Pkg */
            pkg: string;
            /** Folder */
            folder: string;
            status: components["schemas"]["RfqStatus"];
            statusTone: components["schemas"]["Tone"];
            /** Preview */
            preview: string;
            /** Time */
            time: string;
            /**
             * Unread
             * @default false
             */
            unread: boolean;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
        };
        /**
         * RfqConversation
         * @description The full email thread for an RFQ, plus its (possibly updated) status.
         */
        RfqConversation: {
            /** Rfqid */
            rfqId: string;
            status: components["schemas"]["RfqStatus"];
            statusTone: components["schemas"]["Tone"];
            /** Gmail */
            gmail: boolean;
            /** Thread */
            thread: components["schemas"]["ConversationMessage"][];
        };
        /** RfqDetail */
        RfqDetail: {
            /** Id */
            id: string;
            /** Sup */
            sup: string;
            /** Pkg */
            pkg: string;
            /** Folder */
            folder: string;
            status: components["schemas"]["RfqStatus"];
            statusTone: components["schemas"]["Tone"];
            /** Preview */
            preview: string;
            /** Time */
            time: string;
            /**
             * Unread
             * @default false
             */
            unread: boolean;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            /** Thread */
            thread: components["schemas"]["ThreadMessage"][];
        };
        /** RfqFolder */
        RfqFolder: {
            /** Name */
            name: string;
            /** Count */
            count: string;
        };
        /** RfqGenerateRequest */
        RfqGenerateRequest: {
            /** Supplier Ids */
            supplier_ids: string[];
        };
        /** RfqLineItem */
        RfqLineItem: {
            /** N */
            n: string;
            /**
             * Q
             * @default
             */
            q: string;
        };
        /** RfqRecipient */
        RfqRecipient: {
            /** Supplierid */
            supplierId?: string | null;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Sentmessageid */
            sentMessageId?: string | null;
            /** Threadid */
            threadId?: string | null;
        };
        /**
         * RfqStatus
         * @enum {string}
         */
        RfqStatus: "Draft" | "Sent" | "Awaiting" | "Quoted";
        /** RfqUpdate */
        RfqUpdate: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Recipients */
            recipients: components["schemas"]["RfqRecipient"][];
        };
        /**
         * Risk
         * @enum {string}
         */
        Risk: "Low" | "Medium" | "High";
        /** SelectResult */
        SelectResult: {
            /** Quote Id */
            quote_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "RFQs Out" | "Quotes In" | "Plans Review" | "Complete" | "Sourcing";
        /** Supplier */
        Supplier: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Cats */
            cats: string[];
            /** Contact */
            contact: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Web */
            web: string;
            /** Rfq */
            rfq: string;
            rfqTone: components["schemas"]["Tone"];
            /** Last */
            last: string;
            /** Quotes */
            quotes: string;
            /** Quoteval */
            quoteVal: string;
            /** Lead */
            lead: string;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            fin: components["schemas"]["SupplierFinancials"];
        };
        /** SupplierComm */
        SupplierComm: {
            tone: components["schemas"]["Tone"];
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Time */
            time: string;
            /** Icon */
            icon: string;
        };
        /** SupplierDetail */
        SupplierDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Cats */
            cats: string[];
            /** Contact */
            contact: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Web */
            web: string;
            /** Rfq */
            rfq: string;
            rfqTone: components["schemas"]["Tone"];
            /** Last */
            last: string;
            /** Quotes */
            quotes: string;
            /** Quoteval */
            quoteVal: string;
            /** Lead */
            lead: string;
            /** Logo */
            logo: string;
            /** Logobg */
            logoBg: string;
            fin: components["schemas"]["SupplierFinancials"];
            /** Comms */
            comms: components["schemas"]["SupplierComm"][];
        };
        /** SupplierFinancials */
        SupplierFinancials: {
            /** Submitted */
            submitted: string;
            /** Total */
            total: string;
            /** Avg */
            avg: string;
        };
        /** SupplierSearchAccepted */
        SupplierSearchAccepted: {
            /** Status */
            status: string;
            /** Package */
            package: string;
        };
        /** SupplierSearchRequest */
        SupplierSearchRequest: {
            /**
             * Radius Mi
             * @default 75
             */
            radius_mi: number;
        };
        /** SupplierSearchResult */
        SupplierSearchResult: {
            /** Status */
            status: string;
            /**
             * Mocked
             * @default false
             */
            mocked: boolean;
            /**
             * Radiusmi
             * @default 0
             */
            radiusMi: number;
            /**
             * Package
             * @default
             */
            package: string;
            /** Error */
            error?: string | null;
            /**
             * Tiers
             * @default []
             */
            tiers: components["schemas"]["SupplierTier"][];
        };
        /** SupplierTier */
        SupplierTier: {
            /** Tier */
            tier: number;
            /** Label */
            label: string;
            /** Suppliers */
            suppliers: components["schemas"]["FoundSupplier"][];
        };
        /** ThreadMessage */
        ThreadMessage: {
            /** Dir */
            dir: string;
            /** Who */
            who: string;
            /** Initials */
            initials: string;
            /** Time */
            time: string;
            /** Body */
            body: string;
            /** Subject */
            subject?: string | null;
            /** Attach */
            attach?: string | null;
            /** Logobg */
            logoBg?: string | null;
        };
        /** Timeline */
        Timeline: {
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Gantt */
            gantt: components["schemas"]["GanttBar"][];
            /** Ganttcols */
            ganttCols: string[];
        };
        /**
         * Tone
         * @description Semantic color token consumed by the frontend (maps to a CSS variable).
         * @enum {string}
         */
        Tone: "blue" | "violet" | "gray" | "success" | "warn" | "danger" | "ai";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_projects__project_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_line_items_api_projects__project_id__line_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_suppliers_api_projects__project_id__suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quotes_api_projects__project_id__quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rfqs_api_projects__project_id__rfqs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rfq"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rfq_folders_api_projects__project_id__rfq_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqFolder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_projects__project_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_projects__project_id__packages__pkg__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                pkg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_comparison_api_projects__project_id__packages__pkg__line_comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                pkg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    award_package_api_projects__project_id__packages__pkg__award_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                pkg: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AwardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwardResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_suppliers_api_projects__project_id__packages__package__search_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierSearchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_found_suppliers_api_projects__project_id__suppliers_found_get: {
        parameters: {
            query: {
                package: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_quotes_api_projects__project_id__quotes_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingest_status_api_projects__project_id__quotes_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteIngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_rfq_api_projects__project_id__packages__package__rfqs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RfqGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedRfq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_generated_rfqs_api_projects__project_id__rfqs_generated_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedRfq"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generated_rfq_api_projects__project_id__rfqs__rfq_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedRfq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_generated_rfq_api_projects__project_id__rfqs__rfq_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RfqUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedRfq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_generated_rfq_api_projects__project_id__rfqs__rfq_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rfq_conversation_api_projects__project_id__rfqs__rfq_id__conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqConversation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_generated_rfq_api_projects__project_id__rfqs__rfq_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedRfq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Supplier"][];
                };
            };
        };
    };
    get_supplier_api_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_types_api_documents_plan_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanType"][];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_line_items_api_documents__document_id__line_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_document_line_items_api_documents__document_id__line_items_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineItemsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineItemGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_document_api_documents__document_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_documents__document_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rfq_api_rfqs__rfq_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RfqDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_rfqs__rfq_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_followup_api_rfqs__rfq_id__followup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rfq_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowupDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_quotes__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_quote_api_quotes__quote_id__select_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
